### ISSUE TITLE
Functionality Checklist

### ISSUE THREAD

**Issue by stephenrparsons** [Lexcelon/batlab-toolkit-gui#24]
- [ ] Notify if Batlab firmware version is below the minimum required
- [ ] Flash arbitrary firmware to Batlab
- [ ] Update Batlab firmware to latest
